# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigWordFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=64)),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
