# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordfrequency',
            name='word',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
