# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20170422_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('feedback', models.TextField(null=True)),
            ],
        ),
    ]
