# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_bigwordfrequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigwordfrequency',
            name='frequency',
            field=models.BigIntegerField(),
        ),
    ]
