# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20170711_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigwordfrequency',
            name='frequency',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
