# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20170717_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordfrequency',
            name='frequency',
            field=models.IntegerField(db_index=True),
        ),
    ]
